/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Design;

/**
 *
 * @author USER
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        bookTickets = new javax.swing.JButton();
        login = new javax.swing.JButton();
        resister = new javax.swing.JButton();
        aboutUs = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(1229, 632));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(153, 153, 0));
        title.setText("              Online Train Tickets Management System");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 40));

        home.setBackground(new java.awt.Color(0, 204, 51));
        home.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        home.setForeground(new java.awt.Color(0, 153, 51));
        home.setText("   Home");
        home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 40));

        bookTickets.setBackground(new java.awt.Color(0, 204, 51));
        bookTickets.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        bookTickets.setForeground(new java.awt.Color(0, 153, 51));
        bookTickets.setText("   Book Tickets");
        bookTickets.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTicketsActionPerformed(evt);
            }
        });
        getContentPane().add(bookTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 220, 40));

        login.setBackground(new java.awt.Color(0, 204, 51));
        login.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(0, 153, 51));
        login.setText("   Login");
        login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 210, 40));

        resister.setBackground(new java.awt.Color(0, 204, 51));
        resister.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        resister.setForeground(new java.awt.Color(0, 153, 51));
        resister.setText("  Resister");
        resister.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resisterActionPerformed(evt);
            }
        });
        getContentPane().add(resister, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 200, 40));

        aboutUs.setBackground(new java.awt.Color(0, 204, 51));
        aboutUs.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        aboutUs.setForeground(new java.awt.Color(0, 153, 51));
        aboutUs.setText("    About Us");
        aboutUs.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsActionPerformed(evt);
            }
        });
        getContentPane().add(aboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 190, 40));

        Logout.setBackground(new java.awt.Color(0, 204, 51));
        Logout.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        Logout.setForeground(new java.awt.Color(0, 153, 51));
        Logout.setText("   Train Time");
        Logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/picture/newtrain2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AboutUs.main(new String[0]);
    }//GEN-LAST:event_aboutUsActionPerformed

    private void resisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resisterActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Resister.main(new String[0]);
    }//GEN-LAST:event_resisterActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        setVisible(false);
         Login.main(new String[0]);
    }//GEN-LAST:event_loginActionPerformed

    private void bookTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTicketsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login
                .main(new String[0]);
    }//GEN-LAST:event_bookTicketsActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Train_time.main(new String[0]);
    }//GEN-LAST:event_LogoutActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton aboutUs;
    private javax.swing.JButton bookTickets;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login;
    private javax.swing.JButton resister;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
